
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
		#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"


/* event handler declarations */
void view1_start_stop_onclicked(uib_view1_view_context*, Evas_Object*, void*);

uib_view_context* uib_view_view1_create(Evas_Object* parent, void* create_callback_param) {
	uib_view1_view_context* vc = calloc(1, sizeof(uib_view1_view_context));
	vc->parent = parent;
	vc->view_name = "view1";
	vc->indicator_state = ELM_WIN_INDICATOR_SHOW;
	vc->is_user_view = false;
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	if (!vc->box1) {
		vc->box1= elm_box_add(parent);
		vc->root_container = vc->box1;	}
	uib_views_get_instance()->set_targeted_view((uib_view_context*)vc);

	//bind event handler
	evas_object_smart_callback_add(vc->start_stop, "clicked", (Evas_Smart_Cb)view1_start_stop_onclicked, vc);


	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);

	return (uib_view_context*)vc;
}
void uib_view1_config_SQUARE_320x320_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_view1_view_context* vc = (uib_view1_view_context*)uib_app_manager->find_view_context("view1");
	if(!vc) {
		return;
	}
	if(vc->box1) {
		elm_win_alpha_set(vc->box1, EINA_FALSE);
		elm_box_homogeneous_set(vc->box1, EINA_FALSE);
		elm_box_horizontal_set(vc->box1, EINA_FALSE);
		elm_box_padding_set(vc->box1,0,0);
		evas_object_size_hint_align_set(vc->box1, -1.0, -1.0);
		evas_object_size_hint_weight_set(vc->box1, 1.0, 1.0);
		if (!vc->v0) {
			vc->v0 = elm_label_add(vc->box1);
		}
		if(vc->v0) {
			evas_object_size_hint_align_set(vc->v0, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->v0, 1.0, 1.0);			elm_object_text_set(vc->v0,_UIB_LOCALE("Label"));
			elm_label_line_wrap_set(vc->v0, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->v0,0);
			elm_label_ellipsis_set(vc->v0, EINA_TRUE);
			evas_object_show(vc->v0);
		}
		if (!vc->v1) {
			vc->v1 = elm_label_add(vc->box1);
		}
		if(vc->v1) {
			evas_object_size_hint_align_set(vc->v1, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->v1, 1.0, 1.0);			elm_object_text_set(vc->v1,_UIB_LOCALE("Label"));
			elm_label_line_wrap_set(vc->v1, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->v1,0);
			elm_label_ellipsis_set(vc->v1, EINA_TRUE);
			evas_object_show(vc->v1);
		}
		if (!vc->v2) {
			vc->v2 = elm_label_add(vc->box1);
		}
		if(vc->v2) {
			evas_object_size_hint_align_set(vc->v2, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->v2, 1.0, 1.0);			elm_object_text_set(vc->v2,_UIB_LOCALE("Label"));
			elm_label_line_wrap_set(vc->v2, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->v2,0);
			elm_label_ellipsis_set(vc->v2, EINA_TRUE);
			evas_object_show(vc->v2);
		}
		if (!vc->v3) {
			vc->v3 = elm_label_add(vc->box1);
		}
		if(vc->v3) {
			evas_object_size_hint_align_set(vc->v3, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->v3, 1.0, 1.0);			elm_object_text_set(vc->v3,_UIB_LOCALE("Label"));
			elm_label_line_wrap_set(vc->v3, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->v3,0);
			elm_label_ellipsis_set(vc->v3, EINA_TRUE);
			evas_object_show(vc->v3);
		}
		if (!vc->start_stop) {
			vc->start_stop = elm_button_add(vc->box1);
		}
		if (vc->start_stop) {
			evas_object_size_hint_align_set(vc->start_stop, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->start_stop, 1.0, .1);			elm_object_text_set(vc->start_stop,_UIB_LOCALE("Start/Stop"));
			elm_object_style_set(vc->start_stop,"default");
			evas_object_show(vc->start_stop);
		}
		elm_box_pack_end(vc->box1, vc->v0);
		elm_box_pack_end(vc->box1, vc->v1);
		elm_box_pack_end(vc->box1, vc->v2);
		elm_box_pack_end(vc->box1, vc->v3);
		elm_box_pack_end(vc->box1, vc->start_stop);
		evas_object_show(vc->box1);
	}
}

